:arrow_down: electron@2.0.17
- Downgrade to latest version of Electron 2.0.x
- Revert script/lib/generate-startup-snapshot.js to the state it was in
  prior to the Electron 3 upgrade in
  https://github.com/atom/atom/pull/18603. This change is needed to
  resolve the error shown below:

```
Moving generated startup blob into "./out/Atom Dev.app/Contents/Frameworks/Electron Framework.framework/Resources/v8_context_snapshot.bin"
Error: ENOENT: no such file or directory, rename './out/v8_context_snapshot.bin' -> './out/Atom Dev.app/Contents/Frameworks/Electron Framework.framework/Resources/v8_context_snapshot.bin'
  at Object.fs.renameSync (fs.js:766:18)
  at electronLink.then (./script/lib/generate-startup-snapshot.js:128:10)
  at <anonymous>:null:null
```